### ISSUE TITLE
Problem when using Doctrine Embedded/Embeddable

### ISSUE THREAD

**Issue by teohhanhui** [dunglas/DunglasApiBundle#181] opened 2015-07-20 10:19 UTC
http://doctrine-orm.readthedocs.org/en/latest/tutorials/embeddables.html

Currently it dies at `Dunglas\ApiBundle\JsonLd\Serializer\ItemNormalizer::getIriFromItem`. I think the embedded object should be serialized as a plain object?

**Comment by dunglas** [comment] 2015-07-20 11:03
I never tried to work with embedded objects. But yes it should be serialized as a plain object.

**Comment by teohhanhui** [comment] 2015-07-20 11:44
From my reading of the code it seems like it will even cause problems with other objects that are not Doctrine entities and/or not a "resource" at all (due to `Dunglas\ApiBundle\JsonLd\Serializer\ItemNormalizer::normalize` and `ResourceResolverTrait::guessResource`), or am I missing something?

**Comment by dunglas** [comment] 2015-07-20 11:46
Yes. For now any object exposed must be associated to a `Resource` (in fact should be better called `ResourceType`) class.
The only currently supported way to "embed" raw data structures is associative array.

**Comment by teohhanhui** [comment] 2015-07-20 12:11
It'd be nice if I can use `Symfony\Component\Serializer\Normalizer\ObjectNormalizer` to convert the object into associative array before being passed to `Dunglas\ApiBundle\JsonLd\Serializer\ItemNormalizer`

**Comment by teohhanhui** [comment] 2015-07-20 12:21
But I think the more ideal solution would still be to have it as a `Resource` without `id` (is that valid?)

**Comment by dunglas** [comment] 2015-07-20 12:32
I think it's a better idea to use `ObjectNormalizer`. A `Resource` represent a REST resource (exposed trough an URL), not an internal object (I'll write some doc about the terminology when I'll be less busy).

**Comment by teohhanhui** [comment] 2015-07-20 12:37
For example, if I want to embed [PriceSpecification](http://schema.org/PriceSpecification), how would I go about that? I still want it to be properly identified as such (if at all possible)...

**Comment by dunglas** [comment] 2015-07-20 12:39
In that case you don't need Doctrine Embedded/Embeddable IMO. A typical relation between 2 entities should do the work.

**Comment by theofidry** [comment] 2015-07-20 13:52
I guess it's kind of a duplicate of #166: how to handle entities (embedded or not) which are internal object and not a REST resource.

**Closed** 2015-08-17 04:53 UTC
Labels: duplicate, enhancement
