### ISSUE TITLE
AttributeMetadata should work with getters too

### ISSUE THREAD

**Issue by teohhanhui** [dunglas/DunglasApiBundle#249] opened 2015-08-28 10:25 UTC
Currently it's compulsory to have every attribute as a property, which doesn't make sense in all cases.

Example:

```php
class Product
{
    public function getStatus()
    {
        // dynamically compute status

        return $status;
    }
}
```

**Comment by dunglas** [comment] 2015-08-28 11:07
Are you sure it doesn't work? Because it should: https://github.com/dunglas/DunglasApiBundle/blob/master/Mapping/Loader/ReflectionLoader.php#L86

**Comment by teohhanhui** [comment] 2015-08-28 11:18
It only gets called when normalization/denormalization groups are not set... I'll have to dig deeper, because at the very least `AttributeMetadata::getType()` gives null.

**Comment by dunglas** [comment] 2015-09-03 09:56
The problem is in the `PropertyInfo`. To retrieve the type, a property (and not a getter) must exist: https://github.com/dunglas/php-property-info/blob/master/src/PropertyInfo/PropertyInfoInterface.php

A solution would be to change the parameter type from `\ReflectionProperty` to string and let extractors deal with virtual properties.

**Comment by dunglas** [comment] 2015-09-03 09:57
A workaround for now is to create an (unused) class property called `$status`.

**Comment by dunglas** [comment] 2015-09-25 07:10
Fixed in the new Symfony PropertyInfo component: https://github.com/symfony/symfony/pull/15858

**Closed by dunglas** 2015-09-25 07:10 UTC
