### ISSUE TITLE
Invalid NotFoundHttpException when page is set to 1 and no records are returned

### ISSUE THREAD

**Issue by felicitus** [dunglas/DunglasApiBundle#172] opened 2015-07-16 21:35 UTC
When I do a query where I set the page parameter to 1 and no records are available, the API returns an Exception. I agree that it should throw an exception if no records are found for pages > 1, but it shouldn't do this for page 1, because page 1 could be empty.

**Comment by felicitus** [comment] 2015-07-16 21:37
On a second thought, it would really be nice to disable that exception completely, or a way to revert to the first page if the second page is not available.

**Comment by dunglas** [comment] 2015-07-16 21:50
The problem is that 2 different URLs will be valid for the same resource. But as it is a recurrent request, I'm OK to change that behavior and I'll merge any PR changing it.

**Comment by theofidry** [comment] 2015-07-16 22:02
+1 :)

**Comment by cbourgois** [comment] 2015-08-26 11:08
No problem to disable the exception for page 1, but if the exception is removed for pages > 1, we have to edit `hydra:previousPage` and `hydra:nextPage` to avoid previousPage/nextPage to be superior to lastPage

If I query `/books?page=3`, the response is :
````
{
  "@context": "/contexts/Book",
  "@id": "/books?page=3",
  "@type": "hydra:PagedCollection",
  "hydra:previousPage": "/books?page=2",
  "hydra:nextPage": "/books?page=4",
  "hydra:totalItems": 0,
  "hydra:itemsPerPage": 30,
  "hydra:firstPage": "/books",
  "hydra:lastPage": "/books",
  "hydra:member": []
}
```
`hydra:previousPage` should be set to `/books` and `hydra:nextPage` should not be defined.

**Comment by cbourgois** [comment] 2015-08-27 07:20
It seems that #191 fixes it. The NotFoundHttpException was originally triggered in Controller/ResourceController::cgetAction but this part was removed.

**Comment by theofidry** [comment] 2015-08-27 07:21
Ok, closing the issue then :)

**Closed by theofidry** 2015-08-27 07:21 UTC
